### ISSUE TITLE
it not work in my Centos python2.7,please help

### ISSUE THREAD

**Issue by Jy-Lab** [yanminhui/python-facepp#3]
Traceback (most recent call last):
  File "faceinfo.py", line 8, in <module>
    return_attributes=['age'])
  File "/usr/lib/python2.7/site-packages/facepplib/managers/base.py", line 83, in get
    res = self.facepp.engine.request('post', self.url, data=self.params)
  File "/usr/lib/python2.7/site-packages/facepplib/engines/base.py", line 109, in request
    return self.process_response(response)
  File "/usr/lib/python2.7/site-packages/facepplib/engines/base.py", line 203, in process_response
    raise e if arg_num == 0 else e(error_details)
facepplib.exceptions.ApiNotFound: Requested API can not be found

**Comment by yanminhui** [comment]
> Traceback (most recent call last):
> File "faceinfo.py", line 8, in
> return_attributes=['age'])
> File "/usr/lib/python2.7/site-packages/facepplib/managers/base.py", line 83, in get
> res = self.facepp.engine.request('post', self.url, data=self.params)
> File "/usr/lib/python2.7/site-packages/facepplib/engines/base.py", line 109, in request
> return self.process_response(response)
> File "/usr/lib/python2.7/site-packages/facepplib/engines/base.py", line 203, in process_response
> raise e if arg_num == 0 else e(error_details)
> facepplib.exceptions.ApiNotFound: Requested API can not be found

```.bash
$ pip2 install python-facepp
$ python2.7 -m facepplib
```
在 `Ubuntu` 及 `Mac OS` 上实施以上命令，运行均正常。
可否提供出错信息的前后条件（重现场景）以便排查问题。
